### ISSUE TITLE
Forex Dashboard

### ISSUE THREAD

**Issue by Clemiax** [SH-Stark/trading-dashboard#6]
Hello,

i'm part of a trading bot project based on Forex.

Actually, there is no DIY dashboard for Forex Monitoring and the design of your interface takes it well.

it could be an interesting project !
If you want more information, do not hesitate to contact me through Discord : Clem'#3945 // or by email : contact@btlxcapital . xyz

Thanks by advance,
and Happy New Year !

**Comment by SH-Stark** [comment]
Hey! I added you on Discord. 
Cheers
